steps:
  - id: "Deploying"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "functions"
      - "deploy"
      - "${_PROJECT_NAME}"
      - "--gen2"
      - "--source=."
      - "--trigger-http"
      - "--min-instances=0"
      - "--max-instances=1"
      - "--runtime=nodejs20"
      - "--region=${_REGION}"
      - "--entry-point=service"
      - "--allow-unauthenticated"
      - "--project=${_PROJECT_ID}"
      - "--set-secrets=JWT_SECRET=JWT_SECRET:latest"
      - "--set-env-vars=NODE_ENV=${_NODE_ENV}"
      - "--service-account=${_SERVICE_ACCOUNT}"

options:
  logging: CLOUD_LOGGING_ONLY

tags:
  - master
  - beta
  - develop
